<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap -->
    <link href="/vendor/twbs/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
  	      <a class="navbar-brand" href="#">The Tasklist!</a>
        </div>
      </div>
    </nav>

    <div class="container">
		
		<div class="panel panel-default"> 
			<div class="panel-heading">Minhas tarefas</div>
			
			<div class="panel-body" style="text-align: right;">
				<p><button data-toggle="modal" data-target="#myModal" type="button" class="btn btn-success"><span class="glyphicon glyphicon-star" aria-hidden="true"></span> Cadastrar tarefa</button></p>	
			</div>
		
			<table class="table">
				<thead>
					<tr>
						<th>#</th>
						<th>Título</th>		
						<th>Tarefa</th>
						<th>Cadastro</th>
						<th>Prazo</th>
						<th>Status</th>
						<th>Ações</th>
					</tr>
				</thead>
				<tbody>
				<?php foreach($tasks as $k => $task) { ?>
					<tr>
						<th scope="row"><?php echo ($k+1); ?></th>
						<td><?php echo $task->titulo; ?></td> 
						<td><?php echo $task->task; ?></td> 
						<td><?php 
							$cadastro = new DateTime($task->cadastro->date);
							echo $cadastro->format('d/m/Y'); 
						?></td>
						<td><?php 
							$prazo = new DateTime($task->prazo->date);
							echo $prazo->format('d/m/Y'); 
						?></td>
						<td><?php echo $task->status; ?></td>
						<td>
							<a href="/ver/<?php echo $task->id; ?>" class="btn btn-warning btn-xs">
								<span class="glyphicon glyphicon-zoom-in" aria-hidden="true"></span>
								Ver
							</a>
							<a href="/editar/<?php echo $task->id; ?>" class="btn btn-primary btn-xs">
								<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
								Editar
							</a>
							<a href="/deletar/<?php echo $task->id; ?>" type="button" class="btn btn-danger btn-xs" data-rel="<?php echo $task->id; ?>">
								<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
								Deletar
							</a>
						</td>
					</tr>
				<?php } ?>
		 		</tbody>
			</table>
			</div>
		</div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/vendor/twbs/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="/App/assets/functions.js"></script>
    
	<!-- Modal -->
	<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title" id="myModalLabel">Criar tarefa</h4>
	      </div>
	      <div class="modal-body">
	        <form id="form-task" method="post" action="/">
	      	<input type="hidden" name="id" id="id" value="<?php echo @$taskToEdit->id; ?>">
		        <div class="form-group"> 
		        	<label for="titulo">Título</label>
		        	<input type="text" class="form-control" name="titulo" id="titulo" required="required" value="<?php echo @$taskToEdit->titulo; ?>">
		      	</div>	
		        <div class="form-group">
		        	<label for="prazo">Tarefa</label> 
		        	<textarea required="required" class="form-control" name="task" id="task" placeholder="Descrição completa"><?php echo @$taskToEdit->task; ?></textarea>
		      	</div>	
		        <div class="form-group"> 
		        	<label for="prazo">Prazo</label>
		        	<?php $prazo = new DateTime(@$taskToEdit->prazo->date); ?>
		        	<input type="date" class="form-control" id="prazo" name="prazo" placeholder="Prazo" required="required" value="<?php echo @$prazo->format('Y-m-d') ?>">
		      	</div>	
		        <div class="form-group"> 
		        	<label for="prazo">Status</label>
		        	<select name="status"required="required" id="status" class="form-control">
		        		<option <?php if (@$taskToEdit->status === 'Não iniciada') echo 'Selected'; ?>>Não iniciada</option>
		        		<option <?php if (@$taskToEdit->status === 'Em andamento') echo 'Selected'; ?>>Em andamento</option>
		        		<option <?php if (@$taskToEdit->status === 'Concluida') echo 'Selected'; ?>>Concluida</option>
		        		<option <?php if (@$taskToEdit->status === 'Removida') echo 'Selected'; ?>>Removida</option>
		        	</select>
		      	</div>	
	      	
		      <div class="modal-footer">
		        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
		        <button type="submit" class="btn btn-primary">Salvar</button>
		      </div>
	       </form>
	       </div>
	    </div>
	  </div>
	</div>

<?php
if (isset($taskToEdit)) { ?>
	<script>
	$(document).ready(function() {
		$('#myModal').modal('show');
	});
	</script>
<?php } ?>

<?php
if (isset($taskToView)) { ?>

<!-- Modal -->
	<div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title" id="myModalLabel"><?php echo $taskToView->titulo; ?></h4>
	      </div>
	      <div class="modal-body">
	        
		        <div class="form-group">
		        	<label for="prazo">Tarefa</label> 
		        	<?php echo $taskToView->task ?>
		      	</div>	
		        <div class="form-group"> 
		        	<label for="prazo">Prazo</label>
		        	<?php $prazo = new DateTime(@$taskToView->prazo->date);
		        	echo $prazo->format('d/m/Y');
		        	?>
		      	</div>	
		        <div class="form-group"> 
		        	<label for="prazo">Status</label>
		        	<?php echo $taskToView->status; ?>
		      	</div>	
	      	
		      <div class="modal-footer">
		        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>	
		      </div>
	       </div>
	    </div>
	  </div>
	</div>

	<script>
	$(document).ready(function() {
		$('#myModal2').modal('show');
	});
	</script>
<?php } ?>
    
  </body>
</html>
